name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin' # You can choose a different distribution if needed

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test --scan -s

      - name: Collect Test Coverage
        run: ./gradlew jacocoTestReport
        if: always() # Even if the build or tests fail

      - name: Code Quality Check
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test/

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        if: always() # Even if the build or tests fail
        with:
          name: code-coverage
          path: build/reports/jacoco/test/html/